export const FETCH_RECIPES = 'FETCH_RECIPES';
export const UPDATE_SEARCH_KEYWORD = 'UPDATE_SEARCH_KEYWORD';
export const UPDATE_SELECTED_CATEGORIES = 'UPDATE_SELECTED_CATEGORIES';
export const REMOVE_SELECTED_CATEGORY = 'REMOVE_SELECTED_CATEGORY';